[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core", package = "core", features = ["bevy"] }
bevy = { version = "0.18", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_state",
    "bevy_window",
    "bevy_asset",
    "bevy_winit",
    "bevy_pbr",
    "bevy_gizmos",
    "x11",
    "png",
] }
serde = { version = "1", features = ["derive"] }
