[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer = { path = "../renderer" }
core = { path = "../core", package = "core" }
time = { path = "../time" }
worldgen = { path = "../worldgen" }
bevy = { version = "0.18", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_state",
    "bevy_window",
    "bevy_asset",
    "bevy_winit",
    "bevy_pbr",
] }

[features]
default = []
dev = ["bevy/dynamic_linking"]
